Uploading/editing dats file
bento-platform/bento_web pull request #192
Opened 2022-12-12 20:55 UTC by SanjeevLakhwani

Now one can upload and edit dats-file which is also checked whether the file is a proper json

2022-12-13 15:51 UTC, davidlougheed commented
the DATS file is stored as stringified JSON in katsu right now unfortunately, yeah
it really should not be... but that's a katsu change

2022-12-13 15:52 UTC, davidlougheed requested changes

2022-12-13 15:52 UTC, davidlougheed commented on src/components/datasets/DatasetForm.js
> +
needless whitespace changes

2022-12-13 15:52 UTC, davidlougheed commented on src/components/datasets/DatasetForm.js
> +                 initialValue: (initialValue || { contact_info: "" }).contact_info || "",
whitespace

2022-12-13 15:52 UTC, davidlougheed commented on src/components/datasets/DatasetForm.js
> +
whitespace

2022-12-13 15:52 UTC, davidlougheed commented on src/components/datasets/DatasetForm.js
> +                        (initialValue || { description: "" }).description || "",
if youre changing this line, use null coalescing here like with title

2022-12-13 15:52 UTC, davidlougheed commented on src/components/datasets/DatasetForm.js
> +
whitespace

2022-12-19 17:21 UTC, gsfk approved these changes

2022-12-19 17:23 UTC, merged