Search summary modal, csv feedback
bento-platform/bento_web pull request #214
Opened 2023-02-02 21:13 UTC by SanjeevLakhwani

- Added search summary modal
- Added feedback when you export a csv

2023-02-07 17:14 UTC, davidlougheed requested changes

2023-03-02 20:34 UTC, SanjeevLakhwani commented on src/components/explorer/SearchSummaryModal.js
> +/* eslint-disable camelcase */
line 25: `const ids = searchResults.results.results.map(({ subject_id }) => subject_id);`

2023-03-02 20:35 UTC, SanjeevLakhwani commented on src/components/explorer/SearchSummaryModal.js
> +                console.log("what i got", result);
removed it

2023-03-02 20:35 UTC, SanjeevLakhwani commented on src/modules/explorer/actions.js
> -import FileSaver from "file-saver";
it is

2023-03-02 20:36 UTC, SanjeevLakhwani commented on src/components/explorer/SearchSummaryModal.js
> +        myHeaders.append("Content-Type", "application/json");
changed it

2023-03-02 20:40 UTC, davidlougheed approved these changes

2023-03-06 15:02 UTC, merged