Fetch-Gohan-Overview fix
bento-platform/bento_web pull request #244
Opened 2023-05-30 21:19 UTC by brouillette

Obtains the gohan url from service artifacts rather than services

2023-05-31 12:38 UTC, davidlougheed requested changes

2023-05-31 12:38 UTC, davidlougheed commented on src/modules/explorer/actions.js
> +    const gohanUrl = getState()?.services?.itemsByArtifact?.gohan?.url;
itemsByArtifact is deprecated; use itemsByKind

2023-05-31 14:27 UTC, v-rocheleau submitted a review, later dismissed
Works locally for me, but there is another gohan action we probably want to change too in [discovery](https://github.com/bento-platform/bento_web/blob/ff5f2bee8cbc30cab8cf729ee0af936f561d9ff8/src/modules/discovery/actions.js#L9)

2023-06-01 15:35 UTC, davidlougheed approved these changes
lgtm

2023-06-01 15:50 UTC, v-rocheleau approved these changes

2023-06-01 15:51 UTC, merged