Features/configurable extra properties schemas
bento-platform/bento_web pull request #260
Opened 2023-06-19 14:19 UTC by noctillion

This PR implements the fetching of extra properties schema types. It allows retrieval of schema types dynamically from katsu.
The changes include:

- Updates in the actions.js file where a new action fetchExtraPropertiesSchemaTypes has been defined. This action hits the API endpoint api/extra_properties_schema_types to retrieve the data.
- Updates in the reducers.js file, where handling for the new action types is defined. 
- Updates in the component ProjectJsonSchemaModal that uses the ProjectJsonSchemaForm, where the extraPropertiesSchemaTypes are fetched from the Redux state and passed as a prop to the form component.

2023-06-19 14:33 UTC, davidlougheed requested changes

2023-06-19 14:33 UTC, davidlougheed commented on src/modules/metadata/actions.js
> +    await dispatch(fetchExtraPropertiesSchemaTypes());
this isn't part of fetching projects - this fetch be called elsewhere, upstream of projects being fetched - probably right before this in `fetchUserDependentData` using a Promise.all

2023-06-19 14:33 UTC, davidlougheed commented on src/modules/metadata/reducers.js
> +            // CREATE_PROJECT_JSON_SCHEMA
de-indent

2023-06-19 14:38 UTC, davidlougheed commented
also, could you rebase off of `releases/v2.1` and set that branch as the merge target? @noctillion

2023-06-19 14:42 UTC, noctillion commented
Sure thing! I will do it; thanks for the insights!

2023-06-20 20:16 UTC, noctillion commented
implemented in PR#264

2023-06-20 20:16 UTC, closed without merging