[WIP] refact: convert discovery search form to ant 4
bento-platform/bento_web pull request #373
Opened 2024-03-05 19:43 UTC by davidlougheed

2024-03-07 16:54 UTC, v-rocheleau commented on src/components/discovery/DiscoverySearchCondition.js
> +    const handleField = useCallback((value) => {
I would use a different name for the value callback argument, since "value" is one of the component's props too

2024-03-07 17:36 UTC, davidlougheed commented
need to fix: clicking from charts doesn't work for Julian

2024-03-07 18:26 UTC, v-rocheleau requested changes

2024-03-07 18:26 UTC, v-rocheleau commented on src/components/discovery/DiscoverySearchCondition.js
Degradation in the condition validation.
Previously the explorer would validate that a search value exists for a condition.
Now the user can submit a search request with empty condition values, then fail silently.

2024-03-08 17:22 UTC, v-rocheleau requested changes
Looks good and behaves as expected, besides two minor comments

2024-03-08 17:22 UTC, v-rocheleau commented on src/components/discovery/DiscoverySearchForm.js
> +        return Promise.reject(`This field is must have a value: ${field}`);
Phrasing

2024-03-08 17:22 UTC, v-rocheleau commented on src/components/discovery/DiscoverySearchForm.js
> +        return Promise.reject(`This field is must have a value: ${field}`);
Validation: we may want to prevent users from submitting white-space search values

2024-03-08 17:33 UTC, noctillion approved these changes
Looks good to me. Changes work as expected.

2024-03-08 17:38 UTC, v-rocheleau approved these changes
lgtm!

2024-03-08 17:40 UTC, merged