Update IndividualVariants.js
bento-platform/bento_web pull request #401
Opened 2024-05-03 16:31 UTC by noctillion

fix pass symbol to setIgvPosition

2024-05-03 16:46 UTC, davidlougheed approved these changes
matches spec.

2024-05-03 18:08 UTC, gsfk requested changes
Bit of a puzzle here for me. which I didn't notice when I wrote this ticket. 

The relevant field of phenopackets is [GeneDescriptor](https://phenopacket-schema.readthedocs.io/en/latest/gene.html#rstgene) (aka "gene_context") but the code in web here seems to be for [variant expression](https://phenopacket-schema.readthedocs.io/en/latest/variant.html#rstexpression), which does not have a `gene_context` field (doesn't have `value_id` or `symbol` either)

So the relevant component to change is actually [GeneDesciptor.js](https://github.com/bento-platform/bento_web/blob/master/src/components/explorer/IndividualGenes.js#L31-L48). And we should consider removing the dead code, unless as is always possible, I completely misunderstood.

Also a smaller quibble that the clickable link should actually show the symbol and not the value_id.

2024-05-03 18:13 UTC, davidlougheed commented
hmm yeah its true that this is actually odd despite being functional... @v-rocheleau what is the context here for the duplicate gene context passing?

2024-05-03 18:15 UTC, gsfk commented
Looking at the code it seems like gene_context is pulled from variationDescriptor.gene_context

2024-06-05 20:25 UTC, v-rocheleau requested changes
There was no good reason for the duplicate `gene_context` when I implemented it, other than my poor understanding of igv.

2024-06-05 20:25 UTC, v-rocheleau commented on src/components/explorer/IndividualVariants.js
> +const VariantExpressionDetails = ({variantExpression}) => {
Can be wrapped in a `memo`

2024-06-05 20:25 UTC, v-rocheleau commented on src/components/explorer/IndividualVariants.js
> +const VariantExpressionDetails = ({variantExpression}) => {
Also modify the rendering code to remove the `gene_context` prop (line 64) and conditional render (line 61)

2024-06-19 20:00 UTC, v-rocheleau approved these changes
Lgtm

2024-06-20 18:24 UTC, merged