[WIP] feat: integrate reference service 0.2.0 features
bento-platform/bento_web pull request #405
Opened 2024-05-23 15:44 UTC by davidlougheed

2024-05-30 19:52 UTC, gsfk reviewed
Really nice, I like the tags in the autocomplete options... good enough that you might be able to remove `TODOs: style options` at the top of LocusSearch.js. The tag disappears when you select an option, not sure if that's deliberate. It might be worth keeping.

Just one thing is broken though. Since so many of our instances have only one assembly, the variants search form is supposed to autofill the "Assembly ID" field in the form if there's only one assembly available, rather than forcing you to go through a select menu with only one item. It seems like the form is not re-rendering.

2024-05-31 16:29 UTC, davidlougheed commented
tag disappearing I don't have much of a choice on because of how the autocomplete element works / the logic that extracts the coordinates from the text itself... auto-selecting the assembly ID should be fixed now.

2024-05-31 20:33 UTC, gsfk approved these changes
Working now. 

Weirdly it's possible to do a custom render of the selected option in antd `Select` but not antd `Autocomplete`, despite how similar they are. This isn't the first time this component has let me down.

2024-06-05 19:49 UTC, v-rocheleau requested changes
looks good, small comments

2024-06-05 19:49 UTC, v-rocheleau commented on src/components/discovery/LocusSearch.js
> +        && inputValue.length && (inputValue.includes(" ") || !inputValue.includes(":"));
minor: useMemo

2024-06-05 19:49 UTC, v-rocheleau commented on src/components/explorer/IndividualTracks.js
> +    const igvGenomesByID = useMemo(
Would it be worth it to have this in the redux store?

2024-06-05 19:49 UTC, v-rocheleau commented on src/modules/reference/hooks.js
> +                const res = await fetch(searchUrl, { headers: { Accept: "application/json" } });
Are we sure the reference service will always be public? If not, we should pass the auth headers as well.

2024-06-05 19:49 UTC, v-rocheleau commented on src/components/discovery/LocusSearch.js
> +        if (!inputValue.includes(" ") && inputValue.includes(":")) {
minor: could factor out `inputValue.includes(" ")`, `inputValue.includes(":")` into constants for reuse here and to compute `showAutoCompleteOptions`

2024-06-10 15:10 UTC, v-rocheleau approved these changes
lgtm!

2024-06-10 20:07 UTC, merged