refact: split up manager drop box content into component files
bento-platform/bento_web pull request #439
Opened 2024-09-10 16:28 UTC by davidlougheed

2024-09-10 19:37 UTC, v-rocheleau requested changes

2024-09-10 19:37 UTC, v-rocheleau commented on src/components/manager/dropBox/FileUploadModal.tsx
> +      // If we just re-opened the model, reset the fields
typo: model -> modal

2024-09-10 19:37 UTC, v-rocheleau commented on src/components/manager/dropBox/FileUploadForm.js
Can we make this a `.tsx` file?

2024-09-10 19:37 UTC, v-rocheleau commented on src/components/manager/dropBox/FileContentsModal.js
Can we make this a `.tsx` file?

2024-09-10 19:45 UTC, davidlougheed commented on src/components/manager/dropBox/FileUploadForm.js
typing for the file upload events is a bit odd but i'll give it a shot

2024-09-10 19:53 UTC, davidlougheed commented on src/components/manager/dropBox/FileContentsModal.js
will do!

2024-09-10 19:53 UTC, v-rocheleau commented on src/components/manager/dropBox/FileUploadForm.js
Im fine with js if typing it is too much trouble

2024-09-10 20:20 UTC, davidlougheed commented on src/components/manager/dropBox/FileUploadForm.js
done!

2024-09-11 16:16 UTC, v-rocheleau requested changes
Minor request, otherwise lgtm!

2024-09-11 16:16 UTC, v-rocheleau commented on src/components/manager/dropBox/FileContentsModal.tsx
> +type FileContentsModalType = {
Would rename this to `FileContentsModalProps` for consistency

2024-09-11 17:14 UTC, v-rocheleau approved these changes
LGTM!

2024-09-11 17:56 UTC, merged